### ISSUE TITLE
CTSM51 control: ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_(1850AD,1850pAD,1850)

### ISSUE THREAD

**Issue by olyson** [NCAR/LMWG_dev#1]
**Description:**
Control I1850 spinup sequence simulations (accelerated decomposition (AD), post-AD, production) using cesm2_3_alpha16b (ctsm5.1.dev130).  
Purpose is to provide a control using an up to date tag for comparison with perturbed parameter simulations focused on improving vegetation viability at high northern latitudes.
___
**Case directory:**
Locally:
/glade/work/oleson/cesm2_3_alpha16b/cime/scripts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_(1850AD, 1850pAD, 1850)
___
**Sandbox:**
Locally:
 /glade/work/oleson/cesm2_3_alpha16b
 ___
**user_nl_clm changes:**

hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
 ___
**SourceMods:**

src.clm/atm2lndType.F90:            Add some additional history fields
src.clm/clm_varpar.F90:                nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90:                 Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90:   Add some additional history fields
___
**Diagnostics:**
Diags (if available)
___
**Output:**
Output:
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850AD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850pAD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850/
___
**Contacts:**
@olyson
___
**Extra details:**
See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 2.13% disequilibrium, 240 years
pAD spunup to 3.01% disequilibrium, 800 years
Complete

**Comment by wwieder** [comment]
@olyson I'm assuming that along with a HIST run for #4 we'll want a clean control.
