### ISSUE TITLE
Coupled Sturm snow (b.e23_alpha16b.BLT1850.ne30_t232.034BGC_SturmSnowtk)

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#11]
**Description:**
This simulation NOT STARTED but saving in case we decide to proceed later.

Same as b.e23_alpha16b.BLT1850.ne30_t232.034 (cloned) but with Sturm 1997 calculation of snow thermal conductivity instead of the default. Similar to the coupled case in #6 but here with BGC. Similar to the offline case in #4 but here we run coupled.

Purpose is essentially the same as #4, as relates to discussion #3:
See if increased vegetation at high northern latitudes can lower albedo in spring/early summer and cause earlier melt-out of the snowpack, and warm up the simulation at these latitudes.
___
**Case directory:**
Locally:
/glade/u/home/slevis/cases_LMWG_dev/$CASE
___
**Sandbox:**
Locally:
/glade/work/hannay/cesm_tags/cesm2_3_alpha16b

 ___
**user_nl_ changes:**
Same as #6:
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'

 ___
**SourceMods:**
/glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_SturmSnowtk/SourceMods/src.clm/SoilTemperatureMod.F90
plus mods found in #6:
clm_varpar.F90, surfrdMod.F90 mods for reading a ctsm5.2 fsurdat file
and src.cam:
clubb_intr.F90  hb_diff.F90  vertical_diffusion.F90

___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I1850/$CASE/lnd/)
___
**Output:**
Output (if still available):
/glade/scratch/$USER/archive/$CASE/
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
Before I start the simulation, **I would like feedback on CLM Initial Conditions. Two options:**
1) Start from @olyson's offline case #4, which has some vegetation growing in the Arctic and @olyson recommended this file:
/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc
2) B-case ICs (same as were used in Cecile's case that #6 cloned), so less or no veg growing in Arctic, and turn on reseeding

**Comment by wwieder** [comment]
The plan above looks good.

@dlawrenncar were talking after the CLM meeting and wondered if it makes sense to do with with an F1850 case instead, mainly to 1) save on costs, 2) get higher throughput and 3) avoid a Lab Sea freeze potentially cold model bias in the fully coupled model?

Does this make sense, instead of a B-case?

**Comment by slevis-lmwg** [comment]
Makes sense unless there was ever any suspicion of a land-atm-ocn feedback causing the Lab Sea freeze :-) Let me know what you prefer. Also...

@olyson and I discussed two options for initial conditions to start this case (see above). I'm leaning in favor of option 1 because we will start from a more vegetated state, and we will start by seeing whether the climate can maintain it. I'm interested in feedback on this.

**Comment by slevis-lmwg** [comment]
I am refraining from starting work on this case until I hear whether it should be a B-case or an F-case.

**Comment by olyson** [comment]
F-case seems like a reasonable idea.  You'll need another run as well, a control run.  And maybe you could do the runs with a f09 grid.  I've been doing SE30 to match the to-be-workhorse resolution, but it would be easier to not have to regrid everything all the time for these types of experiments.

**Comment by wwieder** [comment]
Isla agreed that an F case makes sense.  I still think we want to do this with 1850 SSTs, but maybe that's not realistic (I'm not sure what SSTs would be used for an F-1850) If Adam or Cecile don't have recommendations maybe we just do an F2000 case instead?

Keith the grid idea seems reasonable, but is the new CAM physics, tuning, & dycore set up for SE30?
Sam, can you ask some of the CAM developers about both the compset and grid?

**Comment by dlawrenncar** [comment]
I think that there is a small probability that the land vegetation feedback
is contributing to the Lab Sea freeze problem, but it is reasonable to
start with investigations in land-atmosphere only for now.  If we produce a
version with healthier vegetation and earlier snow melt, then we can plug
this back into the coupled system to see if it makes an impact.  Recent
discussions across CESM imiply to me that what we do on land is unlikely to
be a big contributor to solving the problem.

**Comment by slevis-lmwg** [comment]
> Isla agreed that an F case makes sense. I still think we want to do this with 1850 SSTs, but maybe that's not realistic (I'm not sure what SSTs would be used for an F-1850) If Adam or Cecile don't have recommendations maybe we just do an F2000 case instead?
> 
> @olyson the grid idea seems reasonable, but is the new CAM physics, tuning, & dycore set up for SE30? @slevis-lmwg , can you ask some of the CAM developers about both the compset and grid? If an F1850 compset seems complicated to set up, lets just do an F2000.

@adamrher we seek feedback regarding an F-case. I will summarize @wwieder's comments in two bullets:
1) What SSTs does F1850 use? Is it complicated to set up F1850 with 1850 SSTs? Is it easier to setup F2000 in that respect?
2) Is it reasonable to run on the f09 grid or is CAM best tuned for SE30? From our point of view, f09 is easier to postprocess.

@adamrher you can (though you probably do not need to) read earlier posts for additional context.

PS. I'm mentioning @cecilehannay here, though I believe that she is traveling.

**Comment by slevis-lmwg** [comment]
I'm keeping this issue open in case it comes in handy later.

I'm looking at relevant F compsets (and opened a corresponding issue). 
I see "PRES_DOCN" in the 1850 compsets and suspect that this is what you meant in your post @wwieder:
`./query_config --compsets | grep ' F' | grep 1850 | grep -i cam6`
```
   F1850                : 1850_CAM60_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   F1850_BDRD     : 1850_CAM60_CLM50%BGC_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV_BGC%BDRD
   FWsc1850          : 1850_CAM60%WCSC_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FW1850             : 1850_CAM60%WCTS_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
```
So I'm leaning in favor of the F2000climo compset with BGC added to it, unless I hear otherwise:
`./query_config --compsets | grep ' F' | grep 2000 | grep -i cam6`
   F2000climo           : 2000_CAM60_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FSCAM                : 2000_CAM60%SCAM_CLM50%SP_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV
   FCSCAM               : 2000_CAM60%SCAM%CCTS1_CLM50%SP_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV
   FC2000climo          : 2000_CAM60%CCTS1_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FC2000climo_HCO      : 2000_CAM60%CCTS1%HEMCO_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FWsc2000climo        : 2000_CAM60%WCSC_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FWma2000climo        : 2000_CAM60%WCCM_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FW2000climo          : 2000_CAM60%WCTS_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FX2000               : 2000_CAM60%WXIE_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
   FLT2000ClimoC6I5Slim : 2000_CAM60_SLIM_CICE5%PRES_DOCN%DOM_SROF_SGLC_SWAV
   FLT2000ClimoC6I6Slim : 2000_CAM60_SLIM_CICE%PRES_DOCN%DOM_SROF_SGLC_SWAV
```
I haven't tried long compset names recently. If they work, I will use:
2000_CAM60_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
