### ISSUE TITLE
Coupled Sturm snow (f2000.ne30_t232.BGC_CROP_SturmSnowtk)

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#13]
**Description:**
Same as #11 but F2000 instead of B1850.

The control (f2000.ne30_t232.BGC_CROP) is #14 and differs in the SourceMods as explained below.

Purpose is same:
See if increased vegetation at high northern latitudes can lower albedo in spring/early summer and cause earlier melt-out of the snowpack, and warm up the simulation at these latitudes.
___
**Case directory:**
Locally:
/glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP_SturmSnowtk

___
**Sandbox:**
Locally:
/glade/work/hannay/cesm_tags/cesm2_3_alpha16b

 ___
**user_nl_ changes:**
Startup same as #6:
```
use_init_interp = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'
```
Continued as hybrid from year 33 to 96:
```
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
reseed_dead_plants = .true.
```
Also user_nl_cam:
```
fincl2 = 'TREFHT'
nhtfrq = 0,-24
mfilt  = 1,1
```
 ___
**SourceMods:**
/glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_SturmSnowtk/SourceMods/src.clm/SoilTemperatureMod.F90
plus mods found in #6:
clm_varpar.F90, surfrdMod.F90 mods for reading a ctsm5.2 fsurdat file
BUT omitted src.cam: clubb_intr.F90  hb_diff.F90  vertical_diffusion.F90 because these output vars not on master list.
Recommended [SourceMods ](https://github.com/NCAR/LMWG_dev/issues/6#issuecomment-1723919799)for next time.

Control case (#14) omits the mods to SoilTemperatureMod.F90.
___
**Diagnostics:**

[f2000.ne30_t232.BGC_CROP_SturmSnowtk-f2000.ne30_t232.BGC_CROP years 77-96](https://webext.cgd.ucar.edu/F2000climo/f2000.ne30_t232.BGC_CROP_SturmSnowtk/lnd/f2000.ne30_t232.BGC_CROP_SturmSnowtk-f2000.ne30_t232.BGC_CROP/setsIndex.html)
___
**Output:**
(if still available)
/glade/scratch/slevis/archive/f2000.ne30_t232.BGC_CROP_SturmSnowtk
/glade/scratch/slevis/archive/f2000.ne30_t232.BGC_CROP  <-- the control
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
`./create_newcase --compset 2000_CAM60_CLM51%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV --res ne30pg3_t232 --case /glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP --run-unsupported`
and
`./create_clone --clone /glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP/ --case /glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP_SturmSnowtk`

CLM Initial Conditions:
@olyson recommended this file from @olyson's offline case #4, which has some vegetation growing in the Arctic:
/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc

**Comment by olyson** [comment]
You might have discussed this, but do we want a CLM51%BGC-Crop compset instead of CLM5?  And do we want to include the new surface dataset?

**Comment by slevis-lmwg** [comment]
Good points. Thanks, Keith.

**Comment by slevis-lmwg** [comment]
@wwieder 
Keith and I resolved the regrid issues with the diag. pkg.
Diagnostics are now posted above for this case.

**Comment by adamrher** [comment]
@wwieder @slevis-lmwg I presume this run was moved into permanent storage (of which I probably don't have read access)? Mind copying this run and the cntl to scratch for me? Thanks.

**Comment by olyson** [comment]
@slevis-lmwg is on PTO this month.
The data are here:

/glade/campaign/cgd/tss/people/slevis/f_cases/f2000.ne30_t232.BGC_CROP_SturmSnowtk
/glade/campaign/cgd/tss/people/slevis/f_cases/f2000.ne30_t232.BGC_CROP

It looks like everyone has read access, but if you have problems, let me know and I'll copy them to my scratch.

**Comment by adamrher** [comment]
Thanks for letting me know, @olyson. I do not have read access to that directory, so pls copy them over to scratch at ur convenience.

**Comment by olyson** [comment]
@adamrher , the data are now available here:

/glade/derecho/scratch/oleson/archive/f2000.ne30_t232.BGC_CROP_SturmSnowtk
/glade/derecho/scratch/oleson/archive/f2000.ne30_t232.BGC_CROP

Note that the SturmSnowtk simulation was just a change to snow thermal conductivity (but with large effects on snow/soil temperatures for example), didn't include any other deadveg changes.

**Comment by adamrher** [comment]
Got it, thanks Keith.
