### ISSUE TITLE
Phenology Triggers (ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_decidphenotrig_1850)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#15]
**Description:**
_Are seasonally deciduous phenology triggers preventing arctic green up?_

Relaxing [requirements for any/all of these switches](https://github.com/ESCOMP/CTSM/blob/1e2e2c35d9568c94eac6cb606f37c18294158682/src/biogeochem/CNPhenologyMod.F90#L1238) in the seasonally deciduous phenology triggers may let plants start greening up earlier.  **See suggestion in *extra details*, below.**

I'd build on the Sturm case, #10
- starting an AD spinup with initial conditions from the postAD Sturm run
- setting reseed=.true.
 
___
Case directory:
Locally:
/glade/work/oleson/cesm2_3_alpha16b/cime/scripts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_decidphenotrig_GSWP3V1_(1850AD, 1850pAD, 1850)

___
Sandbox:
Locally:
/glade/work/oleson/cesm2_3_alpha16b

___
user_nl_ changes:
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
 finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'
___
SourceMods:

src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields
src.clm/SoilTemperatureMod.F90  Sturm Snow tk
src.clm/CNPhenologyMod.F90 decreasing temperature thresholds to -3C, reducing the minimum critical daylength by 25%, doubling the snow threshold (I think to 20 cm)
___
Diagnostics:
[Diags (if available)](https://webext.cgd.ucar.edu/I1850/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_decidphenotrig_1850/lnd/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_decidphenotrig_1850.11_20-ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850.11_20/setsIndex.html)
___
Output:
Output:
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_decidphenotrig_GSWP3V1_1850AD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_decidphenotrig_GSWP3V1_1850pAD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_decidphenotrig_GSWP3V1_1850/

___
Contacts:
@olyson
@wwieder

___
**Extra details:**
I'd just do this with a branch or source mods in CNPhenology

The suggestions below should are just for testing, but would be simple to impliment:
- decreasing temperature thresholds to -3C, 
- reducing the minimum critical daylength by 25%
- doubling the snow threshold (I think to 20 cm)
```
         else if (season_decid_temperate == 0 .and.  onset_gddflag == 1.0_r8 .and. &
                soila10 > SHR_CONST_TKFRZ-3._r8 .and. &
                t_a5min > SHR_CONST_TKFRZ-3._r8 .and. ws_flag==1.0_r8 .and. &
                dayl>min_critical_daylength_onset*0.75_r8 .and. snow_5day<2._r8*snow5d_thresh_for_onset) then
           do_onset = .true.
        end if
```
**Note**, this is likely to change phenology globally, and likely not in good ways. 

See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 2.89% disequilibrium, 240 years
pAD spunup to 5.86% disequilibrium, 440 years
Complete

**Comment by olyson** [comment]
I'll work on this when I'm back on Tues.

**Comment by wwieder** [comment]
Thanks @olyson.  There are 4 new cases for #3, as well as 4 new cases for #23.  I think the dead vegetation issue is likely more important to prioritize, and setting up all the datm cases may be a bit more time consuming.  I'll let you and @slevis-lmwg decide what makes the most sense for running and post processing all of these simulations.  I appreciate your help!

**Comment by slevis-lmwg** [comment]
> I'll work on this when I'm back on Tues.

@olyson I'm starting on this one now and let's see how far I get with @wwieder's requests today. Let's discuss division of the work on Tues. (or Weds at our meeting).

**Comment by slevis-lmwg** [comment]
Looking in /glade/scratch/oleson/archive, I see that you may have already started several of these, so I will wait.

**Comment by olyson** [comment]
Yes, #15, #16, #17, #22 have been started.

**Comment by olyson** [comment]
![ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_decidphenotrig_1850 JJA TLAI polar](https://github.com/NCAR/LMWG_dev/assets/18671367/faf043ce-97cc-45b4-ba23-9e08131740af)
