### ISSUE TITLE
d_max, land only (ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_dmax_1850)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#17]
**Description:**
The coupled and land only PPE projects identified `d_max` (the dry surface layer (DSL) parameter) as a parameter that could help snow melt, although this maybe more important for coupled simulations...

It looks the the default value for d_max is 0.15m, and for this I think we want to use the high side change (0.6m) from the PPE?  @linniahawkins or @aswann can you confirm this?

I'd build on the Sturm case, #10
- starting an AD spinup with initial conditions from the postAD Sturm run
- setting reseed=.true.
 
___
Case directory:
Locally:
/glade/work/oleson/cesm2_3_alpha16b/cime/scripts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_dmax_GSWP3V1_(1850AD, 1850pAD, 1850)

___
Sandbox:
Locally:
/glade/work/oleson/cesm2_3_alpha16b

___
user_nl_ changes:
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
 finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'
paramfile = '/glade/p/cgd/tss/people/oleson/modify_param/ctsm51_params.c211112.nc.dmax.nc'  **(d_max=60 cm)**
___
SourceMods:

src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields
src.clm/SoilTemperatureMod.F90  Sturm Snow tk
___
Diagnostics:
[Diags (if available)](https://webext.cgd.ucar.edu/I1850/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_dmax_1850/lnd/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_dmax_1850.11_20-ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850.11_20/setsIndex.html)
___
Output:
Output:
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_dmax_GSWP3V1_1850AD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_dmax_GSWP3V1_1850pAD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_SturmSnowtk_dmax_GSWP3V1_1850/

___
Contacts:
@olyson
@wwieder

Extra details:
See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 1.88% disequilibrium, 160 years
pAD spunup to 4.78% disequilibrium, 440 years
Complete

**Comment by olyson** [comment]
I'll work on this when I'm back on Tues.

**Comment by aswann** [comment]
I confirmed with Claire that we used the values from Daniel's one at a time PPE, so whatever was used there is what we implemented in our coupled runs. We didn't save a separate version of that spreadsheet.

**Comment by olyson** [comment]
![ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_dmax_1850 JJA TLAI polar](https://github.com/NCAR/LMWG_dev/assets/18671367/a37582ea-f4d5-4f9f-8cf4-a3bc8adfc42f)
