### ISSUE TITLE
GSWP3_sp: ctsm51d142_f19_GSWP3V1_[1850, hist]

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#18]
**Description:**

Assess land model results from an SP case forced with GSWP3 datm.  I'm inclined to do this with a HIST compset that's been spun up for a bit first?  I also think we could do this with with a 1 or 2 degree FV grid (f09... or f19...) 

See discussion #23.

Spin-up:
`./create_newcase --compset I1850Clm51Sp --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_GSWP3V1_1850 --run-unsupported`
Hist: 
`./create_newcase --compset IHistClm51Sp --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_GSWP3V1_hist --run-unsupported`

___
**Case directory:**
Spin-up: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_GSWP3V1_1850
Hist part 1: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_GSWP3V1_hist.1850-1919
Hist: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_GSWP3V1_hist
hist directory is a copy of "hist part 1" with updates to user_nl_clm and env_run.
___
**Sandbox:**
/glade/work/slevis/git/latest_master
git describe: ctsm5.1.dev142
 ___
**user_nl_ changes:**
spin-up: NONE
hist part 1:
```
finidat = '/glade/scratch/slevis/archive/ctsm51d142_f19_GSWP3V1_1850/rest/0021-01-01-00000/ctsm51d142_f19_GSWP3V1_1850.clm2.r.0021-01-01-00000.nc'
use_init_interp = .true.
```
hist: back to NONE; change env_run to hybrid starting in 1920 and cycle datm to 2014
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
Output (if still available):
/glade/scratch/slevis/archive/ctsm51d142_f19_GSWP3V1_1850/
/glade/scratch/slevis/archive/ctsm51d142_f19_GSWP3V1_hist/
___
**Contacts:**
@olyson
@slevis-lmwg 
___
**Extra details:**
Spin-up phase:
20 years with DATM_YR_START 1901 and DATM_YR_END 1920.
Hist part 1: 1850-1919 with DATM_YR_START 1901, DATM_YR_END 1920, and DATM_YR_ALIGN 1901.
Hist: 1920-2014 with DATM_YR_START 1901, DATM_YR_END 2014, and DATM_YR_ALIGN 1901.

**Comment by slevis-lmwg** [comment]
...just occurred to me. Do all GSWP3 runs need to use Keith's mods that fix the 2014 QBOT = 0 (https://github.com/ESCOMP/CTSM/issues/1099)? I looked at QBOT 2013-2014 from 
/glade/scratch/slevis/archive/ctsm51d142_f19_GSWP3V1_hist/lnd/hist
and it looks strange in January of 2014 but not the rest of 2014 (I think).

**Comment by olyson** [comment]
The issue says that QBOT is zero for all of 2014, but I believe that is it zero for all of Jan 2014 (except for the last time slice).  The last time slice of 2013-12 is also zero.
