### ISSUE TITLE
CRU-NCEP-sp: ctsm51d142_f19_CRUv7_[1850, hist]

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#19]
**Description:**

Assess land model results from and SP cased forced with CRU-NCEP datm.  I'm inclined to do this with a HIST compset that's been spun up for a bit first?  I also think we could do this with with a 1 or 2 degree FV grid (f09... or f19...) 

Same as #18 but using CRUv7 instead of GSWP3V1

Spin-up: `./create_newcase --compset 1850_DATM%CRUv7_CLM51%SP_SICE_SOCN_MOSART_SGLC_SWAV --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_CRUv7_1850 --run-unsupported`
Hist: `./create_newcase --compset HIST_DATM%CRUv7_CLM51%SP_SICE_SOCN_MOSART_SGLC_SWAV --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_CRUv7_hist --run-unsupported`
___
**Case directory:**
Spin-up: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUv7_1850
Hist part 1: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUv7_hist.1850-1919
Hist: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUv7_hist
hist directory is a copy of "hist part 1" with updates to user_nl_clm and env_run.
___
**Sandbox:**
/glade/work/slevis/git/latest_master
git describe: ctsm5.1.dev142
 ___
**user_nl_ changes:**
spin-up: NONE
hist part 1: 
```
finidat = '/glade/scratch/slevis/archive/ctsm51d142_f19_CRUv7_1850/rest/0021-01-01-00000/ctsm51d142_f19_CRUv7_1850.clm2.r.0021-01-01-00000.nc'
use_init_interp = .true.
```
hist: back to NONE; change env_run to hybrid starting in 1920 and cycle datm to 2014

 ___
**SourceMods:**
NONE
___
**Diagnostics:**
https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUv7_hist/lnd/ctsm51d142_f19_CRUv7_hist-ctsm51d142_f19_GSWP3V1_hist/setsIndex.html
___
**Output:**
Output (if still available):
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUv7_1850/
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUv7_hist/
___
**Contacts:**
@olyson
@slevis-lmwg 
___
**Extra details:**
Spin-up phase:
20 years with DATM_YR_START 1901 and DATM_YR_END 1920.
Hist part 1: 1850-1919 with DATM_YR_START 1901, DATM_YR_END 1920, and DATM_YR_ALIGN 1901.
Hist: 1920-2014 with DATM_YR_START 1901, DATM_YR_END 2014, and DATM_YR_ALIGN 1901.

**Comment by slevis-lmwg** [comment]
Diagnostics updated.
