### ISSUE TITLE
TRENDY-SP: ctsm51d142_f19_CRUjra_[1850, hist]

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#20]
**Description:**
Assess land model results from and SP cased forced with TRENDY (CRU-JRA) datm.  I'm inclined to do this with a HIST compset that's been spun up for a bit first?  I also think we could do this with with a 1 or 2 degree FV grid (f09... or f19...) 

Same as #18 but with CRUjra. For guidance, looked at Daniel Kennedy's TRENDY case `/glade/u/home/djk2120/ctsm_trendy_2023/sims/TRENDY2023_f09_S3`

Spin-up:
./create_newcase --compset I1850Clm51Sp --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_CRUjra_1850 --run-unsupported
Hist:
./create_newcase --compset IHistClm51Sp --res f19_f19 --case ~/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist --run-unsupported
___
**Case directory:**
Spin-up: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUjra_1850
Hist part 1: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist.1850-1919
Hist: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist
hist directory is a copy of "hist part 1" with updates to user_nl_clm and env_run.
___
**Sandbox:**
/glade/work/slevis/git/latest_master
git describe: ctsm5.1.dev142
 ___
**user_nl_ changes:**

user_nl_clm

spin-up: NONE
hist part 1:
```
finidat = '/glade/scratch/slevis/archive/ctsm51d142_f19_CRUjra_1850/rest/0021-01-01-00000/ctsm51d142_f19_CRUjra_1850.clm2.r.0021-01-01-00000.nc'
use_init_interp = .true.
```
hist: back to NONE; change env_run to hybrid starting in 1920 and cycle datm to 2022

user_nl_datm_streams
```
CLMCRUNCEPv7.Solar:tintalgo = coszen
CLMCRUNCEPv7.Solar:mapalgo = bilinear
CLMCRUNCEPv7.Solar:taxmode = cycle
CLMCRUNCEPv7.Solar:datavars = FSDS_DIRECT Faxa_swdndr,FSDS_DIFFUSE Faxa_swdndf
CLMCRUNCEPv7.Solar:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.Solar:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Solr.1901_cdf5.nc,...FILL_IN_THE_REST_HERE...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Solr.2022_cdf5.nc
CLMCRUNCEPv7.Precip:tintalgo = nearest
CLMCRUNCEPv7.Precip:mapalgo = bilinear
CLMCRUNCEPv7.Precip:taxmode = cycle
CLMCRUNCEPv7.Precip:datavars = PRECTmms Faxa_precn
CLMCRUNCEPv7.Precip:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.Precip:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Prec.1901_cdf5.nc,...FILL_IN_THE_REST_HERE...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Prec.2022_cdf5.nc
CLMCRUNCEPv7.TPQW:tintalgo = linear
CLMCRUNCEPv7.TPQW:mapalgo = bilinear
CLMCRUNCEPv7.TPQW:taxmode = cycle
CLMCRUNCEPv7.TPQW:datavars = QBOT Sa_shum,PSRF Sa_pbot,TBOT Sa_tbot,WIND Sa_wind
CLMCRUNCEPv7.TPQW:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.TPQW:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.TPQWL.1901_cdf5.nc,...FILL_IN_THE_REST_HERE...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.TPQWL.2022_cdf5.nc
```
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUjra_hist/lnd/ctsm51d142_f19_CRUjra_hist-ctsm51d142_f19_GSWP3V1_hist/setsIndex.html
___
**Output:**
Output (if still available):
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUjra_1850/
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist/
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
Spin-up phase:
20 years with DATM_YR_START 1901 and DATM_YR_END 1920.
Hist part 1: 1850-1919 with DATM_YR_START 1901, DATM_YR_END 1920, and DATM_YR_ALIGN 1901.
Hist: 1920-2022 with DATM_YR_START 1901, DATM_YR_END 2022, and DATM_YR_ALIGN 1901.

**Comment by slevis-lmwg** [comment]
Made mesh file for this datm dataset because it didn't exist, yet, as far as I could tell.

**Comment by slevis-lmwg** [comment]
The run fails for now. A few issues that I have resolved:
- Converted the datm files from netcdf4 to cdf5
- In user_nl_datm_streams, I added prefixes Faxa_ and Sa_ to the variable names (error messages were unhelpful)

Latest error says:
` ERROR: (datm_datamode_clmncep_advance): ERROR: cannot compute short-wave down`
I suspect this is because my mesh file has mask = 1 everywhere, while the files contain valid data only over land. I will use the mesh_mask_modifier tool to modify the mask and hope that this fixes the problem.

**Comment by slevis-lmwg** [comment]
Progress! The run fails with a new error beyond where it stopped before.

DATM output stops here:
```
 atm : model date        10101           0
 atm : model date        10101        1800
 atm : model date        10101        3600
 atm : model date        10101        5400
 atm : model date        10101        7200
 atm : model date        10101        9000
(shr_strdata_readstrm) reading file ub: /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Prec.1901_cdf5.nc       2
(shr_strdata_readstrm) reading file ub: /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.TPQWL.1901_cdf5.nc       2
 atm : model date        10101       10800
 atm : model date        10101       12600
 atm : model date        10101       14400
 atm : model date        10101       16200
 atm : model date        10101       18000
 atm : model date        10101       19800
(shr_strdata_readstrm) reading file ub: /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Solr.1901_cdf5.nc       3
 atm : model date        10101       21600
```
I'm guessing the above relates to the lnd-atm coupling frequency.

The error appears in the lnd and cesm log files:
```
# of NaNs =            1
Which are NaNs =  F T F F
NaN found in field Sl_t at gridcell index            2
```
Traceback:
```
lnd_import_export         165  lnd_import_export_utils.F90
lnd_import_export        1170  lnd_import_export.F90
lnd_import_export         761  lnd_import_export.F90
lnd_comp_nuopc_mp         912  lnd_comp_nuopc.F90
```
My current best guess is that this relates to TBOT in CRUJRA having zeros over ocean. In GSWP3 and CRUv7 there's data over ocean. I'm considering two options and would like feedback @olyson @wwieder:
- Set the zeros to 1e36. If you think that this will work, I likely need to do it for most or all variables.
- Fill the zeros with data from elsewhere. From what I can tell, we filled CRUv7 with Qian, so this would be along the same lines.

**Comment by slevis-lmwg** [comment]
Very good point: the mesh file's mask contains ones everywhere. I should run it through the mesh_mask_modifier. (This occurred to me at an earlier stage, and then I forgot it.)

Another question: The files contain FLDS, but Daniel did not seem to use it. I am now thinking that I should use it. Feedback on that?

**Comment by olyson** [comment]
My recollection is that we had decided not to use FLDS in the CRUv7 because of questionable values at high latitudes.  I'm not sure where the downward longwave comes from in CRUJRA.

**Comment by slevis-lmwg** [comment]
It's running now! I kept FLDS out of it, since Daniel did, too.

**Comment by slevis-lmwg** [comment]
Diagnostics posted above

**Comment by wwieder** [comment]
Thanks for getting this done, Sam!  It looks like seasonal maps (set. 2) didn't process or upload correctly (only DJF results shown).  Maybe we can check after the machines are back up.

**Comment by wwieder** [comment]
BTW, arctic runoff looks crazy, but I'm not sure why?

**Comment by slevis-lmwg** [comment]
> BTW, antarctic runoff looks crazy, but I'm not sure why?

Temperature and Precip seem very different and probably wrong over Antarctica.
FSDS in set2 also looks strange.
Given that CRUjra is for use with TRENDY, I wonder if the data in Antarctica are an afterthought.

**Comment by slevis-lmwg** [comment]
Diagnostics updated.

**Comment by wwieder** [comment]
Should we look at ILAMB comparison of GSWP3 & CRU-JRA results, hopefully adding ERA5 when it's available, or just wait for ERA5?

**Comment by wwieder** [comment]
@olyson volunteered to run ilamb on #18, #19, & #20.  We'll wait on ERA5, as these datm inputs are still forthcoming.

**Comment by olyson** [comment]
ILAMB results for GSWP3V1, CRUNCEPV7, and CRUJRA here:

https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_GSWP3V1_hist/lnd/_build_ILAMB2_7_ForcingDatasets/
