### ISSUE TITLE
Sturm_vegMods (ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_(1850AD, 1850pAD, 1850)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#24]
**Description:**
Let's try to do everything we can to keep vegetation alive: Combining Sturm snow, phenology triggers, FUNfracfixers, and frootleaf in an offline simulation (#2, #4, #7, and #15).  

Do we use this spinup as initial conditions for a subsequent F-case (#25 )? 
___
Case directory:
Locally:
/glade/work/oleson/cesm2_3_alpha16b/cime/scripts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_ABCD_GSWP3V1_(1850AD, 1850pAD, 1850)

___
Sandbox:
Locally:
/glade/work/oleson/cesm2_3_alpha16b

___
user_nl_ changes:
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
 finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'
paramfile = '/glade/p/cgd/tss/people/oleson/modify_param/ctsm51_params.c211112.nc.ABCD.nc'
___
SourceMods:

src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields
src.clm/SoilTemperatureMod.F90  Sturm Snow tk
src.clm/CNPhenologyMod.F90 decreasing temperature thresholds to -3C, reducing the minimum critical daylength by 25%, doubling the snow threshold (I think to 20 cm)
___
Diagnostics:
(https://webext.cgd.ucar.edu/I1850/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_1850/lnd/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_1850.11_20-ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850.11_20/setsIndex.html)
___
Output:
Output (if still available):
/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_ABCD_GSWP3V1_1850AD/
/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_ABCD_GSWP3V1_1850pAD/
/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_ABCD_GSWP3V1_1850/

___
Contacts:
@olyson
@wwieder

___
**Extra details:**
My case name lengths are out of control, so I've designated this combination simulation as ABCD, where
A - SturmSnowtk  (implemented via src.clm/SoilTemperatureMod.F90)
B - decidphenotrig (implemented via src.clm/CNPhenologyMod.F90)
C - frootleaf (implemented via ctsm51_params.c211112.nc.ABCD.nc)
D - FUNfracfixers (implemented via ctsm51_params.c211112.nc.ABCD.nc)

See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 2.44% disequilibrium, 280 years
pAD spunup to 4.94% disequilibrium, 800 years
Complete

**Comment by wwieder** [comment]
Thanks @olyson I opted to leaf out the UDM changes out, as they had neglegable impacts on H2O snow and LAI, in #22.

**Comment by olyson** [comment]
Agreed.

**Comment by olyson** [comment]
This is complete. Results at https://github.com/NCAR/LMWG_dev/discussions/3

**Comment by wwieder** [comment]
Thanks Keith,  can you run diagnostics vs. #1 so we can compare the differences for particular fluxes / states?

**Comment by olyson** [comment]
Yes, I've added the link to the diagnostics above.
