### ISSUE TITLE
Coupled Sturm_vegMods (f2000.ne30_t232.BGC_CROP_Sturm_vegMods)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#25]
**Description:**
Let's try to do everything we can to keep vegetation alive: Combining Sturm snow, phenology triggers, FUNfracfixers, and frootleaf (#2, #4, #7, and #15) in an F-case (similar to #13.)  

- Do we need to use results from #24 as initial conditions?
- Regardless, make sure we set reseed = true.
- Make sure we output daily averaged TREFHT on the atmosphere side to assess any impacts on near surface air temperature variability again.

___
**Case directory:**
/glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP_Sturm_vegMods

___
**Sandbox:**
/glade/work/hannay/cesm_tags/cesm2_3_alpha16b

 ___
**user_nl_ changes:**
```
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
finidat = '/glade/scratch/oleson/archive/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/rest/0401-01-01-00000/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD.clm2.r.0401-01-01-00000.nc'
paramfile = '/glade/p/cgd/tss/people/oleson/modify_param/ctsm51_params.c211112.nc.ABCD.nc'
use_init_interp = .true.
reseed_dead_plants = .true.
```
Also user_nl_cam:
```
fincl2 = 'TREFHT'
nhtfrq = 0,-24
mfilt  = 1,1
```
 ___
**SourceMods:**
src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields
src.clm/SoilTemperatureMod.F90 Sturm Snow tk
src.clm/CNPhenologyMod.F90 decreasing temperature thresholds to -3C, reducing the minimum critical daylength by 25%, doubling the snow threshold (I think to 20 cm)

___
**Diagnostics:**
https://webext.cgd.ucar.edu/F2000climo/f2000.ne30_t232.BGC_CROP_Sturm_vegMods/lnd/f2000.ne30_t232.BGC_CROP_Sturm_vegMods.77_96-f2000.ne30_t232.BGC_CROP.77_96/setsIndex.html
___
**Output:**
(if still available):
/glade/scratch/slevis/archive/f2000.ne30_t232.BGC_CROP_Sturm_vegMods/
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
`./create_clone --clone /glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP_SturmSnowtk --case /glade/u/home/slevis/cases_LMWG_dev/f2000.ne30_t232.BGC_CROP_Sturm_vegMods`

Recommended mods https://github.com/NCAR/LMWG_dev/issues/6#issuecomment-1723919799 if also generating a new control, so I assume not for now.

**Comment by olyson** [comment]
Seems like getting initial conditions from #24 is a good idea.  That simulation is underway.

**Comment by olyson** [comment]
@slevis-lmwg , since you ran the other F-cases, would you be able to run this one?
I have a spunup (4.94% disequilibrium) initial file here:
/glade/p/cgd/tss/people/oleson/CLM5_restarts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_1850pAD.clm2.r.0801-01-01-00000.nc

**Comment by wwieder** [comment]
Would ILAMB results on the 3 F-cases (#11, #14 #25) also be helpful here?  Is this possible w/o a transient run?

**Comment by slevis-lmwg** [comment]
I plan on discussing iLamb questions (from here and the sp cases) with Keith on Weds. morning.

**Comment by wwieder** [comment]
Thanks, Sam.  Can one you you also look at the summer LAI plots and (dead area for the control, STURM and SturmABCD f-cases?).

**Comment by olyson** [comment]
I'll do that.

**Comment by wwieder** [comment]
Feedbacks with accelerated snowmelt are stronger in the F case.  You can flip between this plot for the [I-case](https://webext.cgd.ucar.edu/I1850/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_1850/lnd/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_ABCD_1850.11_20-ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850.11_20/set2/set2_JJA_FSNO.png) vs. this one for the [F-case](https://webext.cgd.ucar.edu/F2000climo/f2000.ne30_t232.BGC_CROP_Sturm_vegMods/lnd/f2000.ne30_t232.BGC_CROP_Sturm_vegMods.77_96-f2000.ne30_t232.BGC_CROP.77_96/set2/set2_JJA_FSNO.png)

**Comment by olyson** [comment]
Polar plots of boreal summer TLAI for the three F-cases.  Top is control.  Middle is Sturm only.  Bottom is equivalent to the land-only ABCD. Improvements similar to those seen in the land-only simulations although not as pronounced.  The improvements in dead vegetation compared to the control are:
(0)     Percent Decrease in Sturm dead_veg (km2): -25.895
(0)     Percent Decrease in ABCD dead_veg (km2): -45.1348

![f2000 ne30_t232 BGC_CROP JJA TLAI polar](https://github.com/NCAR/LMWG_dev/assets/18671367/e01847f6-ef78-40ea-b6fa-40921d402239)
![f2000 ne30_t232 BGC_CROP_SturmSnowtk JJA TLAI polar](https://github.com/NCAR/LMWG_dev/assets/18671367/d119db05-5ea8-49f6-8962-2f05e1a857e1)
![f2000 ne30_t232 BGC_CROP_Sturm_vegMods JJA TLAI polar](https://github.com/NCAR/LMWG_dev/assets/18671367/e8db8ac6-d24a-4d81-b5d8-9c90c4ed9b51)

Annual cycle plots with the F-cases designated by "_F".:
![annual_cycle_new_Siberia1_1850](https://github.com/NCAR/LMWG_dev/assets/18671367/327bac70-33d8-4636-8608-1add20191bcc)

![annual_cycle_radiation_new_Siberia1_1850](https://github.com/NCAR/LMWG_dev/assets/18671367/c3e6cab5-a4be-481b-891d-c6e5daeefbaf)

**Comment by wwieder** [comment]
It's fun to click through the maps in different windows and watch the arctic come alive!
Thanks for posting these @olyson and doing the runs, @slevis-lmwg.

The biophysical changes for snowmelt seem pretty subtle compared to the LAI and survival differences in the Sturm vs. Sturm-ABCD runs (blue vs. yellow)
