### ISSUE TITLE
Hillslope Transient BGC 

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#26]
**Description:**
Test run for hillslope with active bgc and transient land use. 
___
**Case directory:**
Locally:
/glade/u/home/swensosc/cases/hillslope_bgc_npft_2_transient/
___
**Sandbox:**
Locally:
 /glade/work/swensosc/ctsm_code/hillslope_hydrology/
 ___
**user_nl_ changes:**
fsurdat = '/glade/work/swensosc/HillslopeHydrology/InputData/Global/surfdata_0.9x1.25_hist_78pfts_CMIP6_1850_HAND_hillslope_geo_params_section_quad_Global_ASTER_gridcell_cdf5.nc'

finidat = '/glade/scratch/swensosc/archive/hillslope_bgc_npft_2_transient/rest/1900-01-01-00000/hillslope_bgc_npft_2_transient.clm2.r.1900-01-01-00000.nc'

!finidat = '/glade/scratch/swensosc/archive/hillslope_bgc_npft_2_postAD/rest/0211-01-01-00000/hillslope_bgc_npft_2_postAD.clm2.r.0211-01-01-00000.nc'

use_init_interp = .true.

use_hillslope = .true.
use_hillslope_routing = .true.

paramfile = '/glade/p/cgd/tss/people/oleson/modify_param/ctsm51_params.c211112.nc.FUNfracfixers.nc'

flanduse_timeseries = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_esmf/ctsm5.2.0/landuse.timeseries_0.9x1.25_hist_78_CMIP6_1850-2015_c230601.nc'
 ___
**SourceMods:**
changes to use ctsm5.2 datasets
clm_varpar.F90
surfrdMod.F90
___
**Diagnostics:**
[Diags (if available)](https://webext.cgd.ucar.edu/I20TR/hillslope_bgc_npft_2_transient/lnd/hillslope_bgc_npft_2_transient.1990_2009-standard_bgc_npft_2_transient.1990_2009/setsIndex.html)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
Output (if still available):
hillslope: /glade/scratch/swensosc/archive/hillslope_bgc_npft_2_transient/lnd/hist/
standard: /glade/scratch/swensosc/archive/standard_bgc_npft_2_transient/lnd/hist/
___
**Contacts:**
@olyson, @swensosc
___
**Extra details:**

**Comment by olyson** [comment]
@swensosc , if you can point me to a tag you want to use for hillslope, and any namelist settings, etc. that are required, I can start setting this up, and maybe at least get some spinup started before the machines go down.

**Comment by wwieder** [comment]
Sean may have already started this successfully. Were you able to check you history output, @swensosc?

**Comment by swensosc** [comment]
yes, it seems to be running properly at this time.
