### ISSUE TITLE
Answer Changing Tag SNICAR (ctsm51d145_2deg_GSWP3V1_hist)

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#28]
**Description:**
For updating the [Answer Changing Tags wiki page](https://github.com/ESCOMP/CTSM/wiki/Answer-changing-tags).

Used script `/glade/work/slevis/Answer_Changing_Tags/setup_run_answer_changing_tags.csh_dev145` to get the case started. (Remove _dev145 from file name to run it.)
___
**Case directory:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev145/cime/scripts/ctsm51d145_2deg_GSWP3V1_hist
backed up part 1 (1850-1919) in
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev145/cime/scripts/ctsm51d145_2deg_GSWP3V1_hist.1850-1919
___
**Sandbox:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev145
 ___
**user_nl_ changes:**
Second attempt starts from #31:
```
 finidat = '/glade/scratch/slevis/archive/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850pAD/rest/0481-01-01-00000/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850pAD.clm2.r.0481-01-01-00000.nc'
 use_init_interp = .true.
```
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
First attempt started with finidat from an SP simulation, so vegetation is problematic:
https://webext.cgd.ucar.edu/I20TR/ctsm51d145_2deg_GSWP3V1_hist/lnd/ctsm51d145_2deg_GSWP3V1_hist.1995_2014-ctsm51_ctsm51d116_2deg_GSWP3V1_hist.1995_2014/setsIndex.html
Second attempt diagnostics:
https://webext.cgd.ucar.edu/I20TR/ctsm51d145_2deg_GSWP3V1_hist/lnd/ctsm51d145_2deg_GSWP3V1_hist-ctsm51_ctsm51d116_2deg_GSWP3V1_hist/setsIndex.html
___
**Output:**
First attempt:
/glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d145_2deg_GSWP3V1_hist/finidat_from_sp
Second attempt:
/glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d145_2deg_GSWP3V1_hist/finidat_from_bgc
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
1850-1919 cycle GSWP3 1901-1920 data
1920-2014 use GSWP3 1901-2014 data

**Comment by slevis-lmwg** [comment]
New diagnostics posted.
TLAI difference looks more reasonable now.

**Comment by wwieder** [comment]
Thanks for correcting this, @slevis-lmwg 

Sorry if I posted this question on a different thread, but @cenlinhe are increases in albedo like this expected (here for Spring, all sky)? [Other diagnostics are here](https://webext.cgd.ucar.edu/I20TR/ctsm51d145_2deg_GSWP3V1_hist/lnd/ctsm51d145_2deg_GSWP3V1_hist-ctsm51_ctsm51d116_2deg_GSWP3V1_hist/setsIndex.html)
![image](https://github.com/NCAR/LMWG_dev/assets/8031012/6ea5388f-6b40-48ae-bf38-4d9ae779b02e)

**Comment by slevis-lmwg** [comment]
Linking @cenlinhe's previous response, posted in https://github.com/ESCOMP/CTSM/pull/1861.

**Comment by wwieder** [comment]
Thanks Sam, I knew I'd asked this elsewhere, but couldn't find it.
