### ISSUE TITLE
dev145 spinup with BGC, CROP, ISOTOPES (ctsm51d145_2deg_GSWP3V1_bgc_crop_1850[AD,pAD])

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#31]
**Description:**
Spinup including isotopes, using dev145 so as to have restart files with the new bgc variable names (eg SOM_AVL instead of AVL_SOM and LIT_MET instead of MET_LIT)
___
**Case directory:**
/glade/u/home/slevis/cases_LMWG_dev/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850[AD,pAD]
___
**Sandbox:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev145
 ___
**user_nl_ changes:**
for AD...
```
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
```
for pAD, same plus the following:
```
 finidat = '/glade/scratch/slevis/archive/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850AD/rest/0241-01-01-00000/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850AD.clm2.r.0241-01-01-00000.nc'
```
___
**SourceMods:**
NONE
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
/glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d145_2deg_GSWP3V1_hist/bgc_spinup/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850AD
/glade/campaign/cgd/tss/people/slevis/ANSWER_CHANGING_TAGS/ctsm51d145_2deg_GSWP3V1_hist/bgc_spinup/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850pAD
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
`./create_newcase --case ~/cases_LMWG_dev/ctsm51d145_2deg_GSWP3V1_bgc_crop_1850AD --compset 1850_DATM%GSWP3v1_CLM51%BGC-CROP_SICE_SOCN_MOSART_SGLC_SWAV --res f19_g17 --run-unsupported`
AD 240 yrs
pAD 480 yrs

**Comment by slevis-lmwg** [comment]
I ran @olyson's `SpinupStability_v10.ncl` on the pAD simulation and got the following:
```
(0)     EQUILIBRIUM SUMMARY
(0)     =======================================================================
(0)     TOTECOSYSC is in equilibrium. Eq. Yr. = 201
(0)     TOTSOMC is in equilibrium. Eq. Yr. = 41
(0)     TOTVEGC is in equilibrium. Eq. Yr. = 121
(0)     TLAI is in equilibrium. Eq. Yr. = 1
(0)     GPP is in equilibrium. Eq. Yr. = 41
(0)     TWS is in equilibrium. Eq. Yr. = 1
(0)     H2OSNO is in equilibrium. Eq. Yr. = 1
(0)     FATAL: Not enough of the land surface is in equilibrium (  5.47% >   3.00%)
```
@wwieder @olyson I would like your feedback about whether to continue the pAD or call it good.

**Comment by olyson** [comment]
I have been spinning to about 5% on all of my simulations for now, because it takes quite a while to get down to 3% and we need timely results for the dead vegetation issue.  I imagine that we'll continue to do spinups as the model changes, so I think I would call yours good enough, in my opinion.
