### ISSUE TITLE
CRU-JRA BGC control w/ SNICAR (ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850AD, 1850pAD, 1850)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#35]
**Description:**
Our CRU-JRA run in #20 an SP case, this would be a BGC control that we can build off of (e.g. #34).
I'm worried that CRU-JRA seems to have [deeper snow](https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUjra_hist/lnd/ctsm51d142_f19_CRUjra_hist-ctsm51d142_f19_GSWP3V1_hist/set3/set3_landf_Russian_Arctic.png) than GSWP3 in some regions, but it would be good to check.

Let's do this from the latest code base so we get the SNICAR updates.  
Should we also be running with Meier roughness (as we want this on for CLM6)? YES
___
Case directory:
Locally:
/glade/work/oleson/ctsm5.1.dev150/cime/scripts/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_(1850AD, 1850pAD, 1850)

___
Sandbox:
Locally:
/glade/work/oleson/ctsm5.1.dev150

___
user_nl_ changes:

use_nl_clm:
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
paramfile = '/glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/ctsm51_params.RMz0.c231011.nc'
z0param_method = 'Meier2022'

user_nl_datm_streams (note "datafiles" strings have been shortened below)
```
CLMCRUNCEPv7.Solar:tintalgo = coszen
CLMCRUNCEPv7.Solar:mapalgo = bilinear
CLMCRUNCEPv7.Solar:taxmode = cycle
CLMCRUNCEPv7.Solar:datavars = FSDS_DIRECT Faxa_swdndr,FSDS_DIFFUSE Faxa_swdndf
CLMCRUNCEPv7.Solar:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.Solar:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Solr.1901_cdf5.nc,...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Solr.2022_cdf5.nc
CLMCRUNCEPv7.Precip:tintalgo = nearest
CLMCRUNCEPv7.Precip:mapalgo = bilinear
CLMCRUNCEPv7.Precip:taxmode = cycle
CLMCRUNCEPv7.Precip:datavars = PRECTmms Faxa_precn
CLMCRUNCEPv7.Precip:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.Precip:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Prec.1901_cdf5.nc,...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.Prec.2022_cdf5.nc
CLMCRUNCEPv7.TPQW:tintalgo = linear
CLMCRUNCEPv7.TPQW:mapalgo = bilinear
CLMCRUNCEPv7.TPQW:taxmode = cycle
CLMCRUNCEPv7.TPQW:datavars = QBOT Sa_shum,PSRF Sa_pbot,TBOT Sa_tbot,WIND Sa_wind
CLMCRUNCEPv7.TPQW:meshfile = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/lnd_mesh_cdf5.nc
CLMCRUNCEPv7.TPQW:datafiles = /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.TPQWL.1901_cdf5.nc,...,/glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.CRUJRA.0.5d.v1.c190604/TRENDY_cdf5/clmforc.TRENDY.c2023_0.5x0.5.TPQWL.2022_cdf5.nc
```
___
SourceMods:

src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields
src.clm/BareGroundFluxesMod.F90 Address issue #2219.
___
Diagnostics:
https://webext.cgd.ucar.edu/I1850/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850/lnd/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850.11_20-ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_1850.11_20/setsIndex.html
___
Output:
/glade/scratch/oleson/archive/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850AD/
/glade/scratch/oleson/archive/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850pAD/
/glade/scratch/oleson/archive/ctsm51_ctsm51d150_ne30pg3ne30pg3mg17_CRUJRA_1850/

___
Contacts:
@olyson

___
**Extra details:**

See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 2.57% disequilibrium, 320 years
pAD spunup to 5.03% disequilibrium, 680 years
Complete for now.

**Comment by olyson** [comment]
I guess we might as well turn on Meier roughness since this is a new control.  I just need to put in a SourceMod for the forcing height issue we found.
