### ISSUE TITLE
Single point snow albedo mods

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#36]
**Description:**

See [comments on the SNICAR PR re. changes](https://github.com/ESCOMP/CTSM/pull/1861) we can consider for snow albedo modification. Once we make a plan forward I'll create new issues in this repo.

Given the possible directions forward, it seems the best plan to investigate snow albedo modifications may be a series of shorter duration runs to assess arctic survival, timing of snowmelt and albedo in AD simulations.  I'm also going to do these for single point cases to start with.

The three sites are:
- Dikson --lat 73.5 --lon 80.5 , 91% Arctic C3 Grass
- Agapa -- lat 71.15 --lon 87.5 , 65% shrub, 34% grass *control case seems to survive*
- Pyasina --lat 73.5 --lon 87.5 , 60% shrub, 38% grass

| Case | modification | notes |
|------| -------------| ------ |
| control_01 | default BGC| ctsm5.1.dev152 |
| control_sp | default SP| ctsm5.1.dev152 |
| Sturm | `snow_thermal_cond_method = 'Sturm1997'` | Sturm, not Jordan |
| sno_age | `xdrdt = 2`  | ctsm51_params.c211112_snowAge.nc |
| snow_ABC| `xdrdt = 2`, `scvng_fct_mlt_sf = 0.5`, `snw_rds_refrz = 1500 `| ctsm51_params.c211112_snowAge_scvgn_rds.nc |
| blk_c | `snicar_snobc_intmix = .true.` | xmlchange `CLM_BLDNML_OPTS -ignore_warnings` & removed namelist from error flag in `controlMod.F90`|
| blk_ABC | `snicar_snobc_intmix = .true.` + ABC from above | as above + ctsm51_params.c211112_snowAge_scvgn_rds.nc|
| blk_ABCD | `fresh_snw_rds_max = 400._r8`  (previously 203) + blk_ABC above  | as above + AerosolMod.F90  |
| Sturm_blk_ABCD |  `snow_thermal_cond_method = 'Sturm1997'` + blk_ABCD above  | as above + Sturm |
| Sturm_blk_ABCD2 |  `xdrdt = 4`, `scvng_fct_mlt_sf = 0.25`  | results nearly same as above  |
| Sturm_blk_ABCD3 |  `xdrdt = 10`, `scvng_fct_mlt_sf = 0.10`  | results nearly same as above |

---
**Final changes inlucded**
*user_nl_clm changes* 
```
snow_thermal_cond_method = 'Sturm1997'
snicar_snobc_intmix = .true.
paramfile = '/glade/scratch/wwieder/deadArctic/ctsm51_params.c211112_snowAge_scvgn_rds.nc'
```

- Default parameter: `xdrdt = 1`, `scvng_fct_mlt_sf = 1`, `snw_rds_refrz = 1000 `
- Parameter changes inlcude: `xdrdt = 2`, `scvng_fct_mlt_sf = 0.5`, `snw_rds_refrz = 1500 `
- snicar_snowbc required: 
  - xmlchange `CLM_BLDNML_OPTS -ignore_warnings` & 
  - removed namelist from error flag in `/glade/u/home/wwieder/CTSM/src/main/controlMod.F90`
 
-`fresh_snw_rds_max = 400._r8`  as SourceMods (e.g., `/glade/scratch/wwieder/deadArctic/Pyasina/Sturm_blk_ABCD/SourceMods/src.clmAerosolMod.F90`)
___
**Diagnostics:**
Diags (if available)

___
**Run directories and Output:**
Output (if still available):
/glade/scratch/wwieder/deadArctic/

___
**Contacts:**
@wwieder

**Comment by wwieder** [comment]
Control case at **Agapa** (shrub point) seems to be dying:
<img width="698" alt="image" src="https://github.com/NCAR/LMWG_dev/assets/8031012/288ffb40-c620-44f5-a02c-2ea054523b3b">
(*note x-axes are not the same to show longer time series of LAI decline with snow ~ 0.8 m in June.)

Similarly, at Dickson (grass point) 
<img width="654" alt="image" src="https://github.com/NCAR/LMWG_dev/assets/8031012/43c8a944-2f80-4a17-be84-0d5be9a6e6b7">

**Comment by olyson** [comment]
Fyi, it looks like you can change fresh_snw_rds_max in the lnd namelist, at least in ctsm5.1.dev150.

**Comment by wwieder** [comment]
![image](https://github.com/NCAR/LMWG_dev/assets/8031012/9575724a-04df-4f40-ba57-e40400f83b7a)
