### ISSUE TITLE
CRUJRA-SP (ctsm51d142_f19_CRUjra_[1850, hist]_flds)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#39]
**Description:**

Given results in #20 and #35 I wonder if we should try using the CRUJRA longwave?  

Initially, a clone of #20 seems logical to see if we see a downward trend (or any other issues) with using the FLDS provided in CRUJRA?  

___
**Case directory:**
Spin-up: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUjra_1850_flds
Hist: /glade/u/home/slevis/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist_flds
___
**Sandbox:**
/glade/work/slevis/git_ctsm_tags/ctsm5.1.dev142

 ___
**user_nl_ changes:**
As in #20 except:
diff between user_nl_datm_streams
```
49c49
< CLMCRUNCEPv7.TPQW:datavars = QBOT Sa_shum,PSRF Sa_pbot,TBOT Sa_tbot,WIND Sa_wind,FLDS Faxa_lwdn
---
> CLMCRUNCEPv7.TPQW:datavars = QBOT Sa_shum,PSRF Sa_pbot,TBOT Sa_tbot,WIND Sa_wind
```
Also user_nl_clm in the hist case here will point to this case's corresponding finidat.
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
With CRUjra FLDS vs. with clm-calculated FLDS:
https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUjra_hist_flds/lnd/ctsm51d142_f19_CRUjra_hist_flds.1995_2014-ctsm51d142_f19_CRUjra_hist.1995_2014/setsIndex.html

With CRUjra FLDS vs. GSWP3, showing trends from 1901 to the present: https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUjra_hist_flds/lnd/ctsm51d142_f19_CRUjra_hist_flds.1995_2014-ctsm51d142_f19_GSWP3V1_hist.1995_2014/setsIndex.html

ILAMB:
https://webext.cgd.ucar.edu/I20TR/ctsm51d142_f19_CRUjra_hist_flds/lnd/_build_ILAMB2_7_ForcingDatasets_flds/

___
**Output:**
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUjra_1850_flds/
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_LMWG_dev/ctsm51d142_f19_CRUjra_hist_flds/
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
Same as #20

**Comment by slevis-lmwg** [comment]
@olyson @wwieder 
I decided to try premium and the run has started!
(So I moved #38 to premium, as well.)

**Comment by wwieder** [comment]
awesome!  any preliminary results (even as an ncview of ncdiff) of
monthly snowdepth or TBOT that we can share at tomorrow's meeting could be
helpful.

I'm working on slides here
<https://docs.google.com/presentation/d/1Y2uYNcWb1RcSY30I6E8J0AboTC0nG6HD9Jtlssu0_Bs/edit?usp=sharing>
.

**Comment by slevis-lmwg** [comment]
@wwieder I just posted diags above. I have not looked at them, yet.
(The simulation finished last night.)

**Comment by slevis-lmwg** [comment]
I added a plot to the slides

**Comment by slevis-lmwg** [comment]
I have started new diagnostics to plot the full trends: 1901-2022

**Comment by slevis-lmwg** [comment]
Full trends should be up. See link above.

**Comment by wwieder** [comment]
Thanks.  [Global FLDS trends ](https://github.com/ESCOMP/CTSM/wiki/Meeting-Notes-2023-Science)seem ok here.
I don't see any glaring issues in the arctic regional plots either.

There seems to be a jump in global FSDS that I don't really understand, but suspect they're related to the transition from CRU to JRA forcing?  I think JRA55 starts in 1958.

**Comment by olyson** [comment]
Sure!

**Comment by wwieder** [comment]
Thanks for posting, Keith.

So does the seasonal cycle of incoming longwave!
<img width="1444" alt="image" src="https://github.com/NCAR/LMWG_dev/assets/8031012/9a6a5d4f-3238-4dfd-8bc2-20ee721e93eb">.
