### ISSUE TITLE
Sturm Snow: ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_(1850AD,1850pAD,1850)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#4]
**Description:**
Test Sturm 1997 calculation of snow thermal conductivity

I've added the snow conductivity calculations from Sturm et al. provided by in this [CTSM discussion](https://github.com/ESCOMP/CTSM/discussions/1960) and described for single point runs by [Dutch et al 2022](https://tc.copernicus.org/articles/16/4201/2022/).  Many thanks to @AdrienDams for doing some preliminary tests with this globally. 

Source mods are here `/glade/u/home/wwieder/CTSM/src/biogeophys/SoilTemperatureMod.F90`.  @olyson, do you want to try a land only case with this SourceMod to investigate soil temperature impacts and arctic vegetation survival?

___
**Case directory:**
Locally:
/glade/work/oleson/cesm2_3_alpha16b/cime/scripts/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_(1850AD, 1850pAD, 1850)
___
**Sandbox:**
Locally:
 /glade/work/oleson/cesm2_3_alpha16b
 ___
**user_nl_ changes:**
hist_fincl1 = 'TOTECOSYSC', 'TOTECOSYSN', 'TOTSOMC', 'TOTSOMN', 'TOTVEGC', 'TOTVEGN', 'TLAI', 'GPP', 'CPOOL', 'NPP', 'TWS', 'H2OSNO','NDEP_TO_SMINN'
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
 ___
**SourceMods:**
src.clm/SoilTemperatureMod.F90: Modify snow thermal conductivity per Sturm
src.clm/atm2lndType.F90: Add some additional history fields
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/Wateratm2lndType.F90: Add some additional history fields

___
**Diagnostics:**
https://webext.cgd.ucar.edu/I1850/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850/lnd/

___
**Output:**
Output (if still available):
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850AD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850pAD/
/glade/campaign/cgd/tss/common/Land_Only_Simulations/CTSM52_DEV/ctsm51_cesm23a16bctsm51d130_ne30pg3ne30pg3mg17_GSWP3V1_SturmSnowtk_1850/
___
**Contacts:**
@olyson
@wwieder 
___
**Extra details:**
See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
AD spunup to 1.73% disequilibrium, 240 years
pAD spunup to 4.62% disequilibrium, 320 years
Complete

**Comment by wwieder** [comment]
@olyson can you run a historical case with this to compare with ILAMB (and a control case)

**Comment by olyson** [comment]
See https://github.com/NCAR/LMWG_dev/issues/29 and https://github.com/NCAR/LMWG_dev/issues/30
