### ISSUE TITLE
Scientific check for MatrixCN vs. AD spinup (ctsm51d159_f45_GSWP3_bgccrop_1850SASU vs. AD)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#45]
**Description:**
Test to ensure results from MatrixCN initialization match those from an AD spinup.  This was done in [Liao et al. 2023](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2023MS003625) with GSWP3 (2005-2014) for a site in Brazil (55°W, 7°S) and using the sparse grid.  [Lu et al. 2020](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020MS002105) also ran a full transient case on the 4x5 grid, illustrating that differences between SASU and AD simulations where nearly identical (relative differences < 1% for nearly all grids).  We want to make sure we're getting similar results with the Matrix code that's been merged up to main now. Let's make a clean test with the modern code base to make sure this is still true (and also to evaluating time savings?)
___
**Case directory:**
Locally:
/glade/u/home/slevis/cases_LMWG_dev/ctsm51d159_f45_GSWP3_bgccrop_1850AD
/glade/u/home/slevis/cases_LMWG_dev/ctsm51d159_f45_GSWP3_bgccrop_1850pAD
/glade/u/home/slevis/cases_LMWG_dev/ctsm51d159_f45_GSWP3_bgccrop_1850SASU
/glade/u/home/slevis/cases_LMWG_dev/ctsm51d159_f45_GSWP3_bgccrop_1850pSASU

Rerun of AD and pAD cases with initial soil temperature set to 272K for vegetated grid cells (and reverted back to 274K for impervious/pervious road).  Also, rerun of SASU and pSASU simulations since the SASU was initialized from the end of the AD simulation (year 200).  Cloned from the original cases above.

/glade/work/oleson/cn-matrix_v3_cases/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850AD
/glade/work/oleson/cn-matrix_v3_cases/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850pAD
/glade/work/oleson/cn-matrix_v3_cases/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850SASU
/glade/work/oleson/cn-matrix_v3_cases/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850pSASU

___
**Sandbox:**
Locally:
/glade/work/slevis/git/cn-matrix_v3
commit 2ea1cecedd3a00cd98d962f9de1eaac2159ace05 (HEAD -> cn-matrix_v3, chrislxj/cn-matrix_v3)
 ___
**user_nl_ changes:**
N.B.(1): matrixcn defaults to .true. in this sandbox
N.B.(2): I didn't think to change snow_thermal_cond_method to Sturm1997 for these runs

SASU user_nl_clm (SASU starts with finidat from AD and pSASU starts with finidat from SASU)
```
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
```
AD same with two additional settings (pAD starts with finidat from AD)
```
use_matrixcn = .false.
use_soil_matrixcn = .false.
```
Differencing the two lnd_in files shows the following (< SASU, > AD):
```
27d26
<  iloop_avg = -999
30d28
<  isspinup = .true.
36,37d33
<  nyr_forcing = 20
<  nyr_sasu = 20
51c47
<  spinup_state = 0
---
>  spinup_state = 2
77c73
<  use_matrixcn = .true.
---
>  use_matrixcn = .false.
81c77
<  use_soil_matrixcn = .true.
---
>  use_soil_matrixcn = .false.
299c295
<  reseed_dead_plants = .false.
---
>  reseed_dead_plants = .true.
```
**Should I worry about the difference in reseed_dead_plants?**
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
Output (if still available):
/glade/derecho/scratch/slevis/archive/ctsm51d159_f45_GSWP3_bgccrop_1850AD
/glade/derecho/scratch/slevis/archive/ctsm51d159_f45_GSWP3_bgccrop_1850pAD
/glade/derecho/scratch/slevis/archive/ctsm51d159_f45_GSWP3_bgccrop_1850SASU
/glade/derecho/scratch/slevis/archive/ctsm51d159_f45_GSWP3_bgccrop_1850pSASU

Rerun of cases with initial soil temperature change:
/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoilini_1850AD
/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoilini_1850pAD
/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoilini_1850SASU
/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoilini_1850pSASU
___
**Contacts:**
@slevis-lmwg @olyson 
___
**Extra details:**
I created the cases with the `1850_DATM%GSWP3v1_CLM51%BGC-CROP_SICE_SOCN_SROF_SGLC_SWAV` compset.
I included isotopes, as in #31, in case these simulations become baselines for follow-up simulations.
The plan, based on [this post below](https://github.com/NCAR/LMWG_dev/issues/45#issuecomment-1877951877), is:
AD 200 yrs (done) --> SASU 160 (done) --> pSASU 40 (done)
AD 200 yrs (done) --> pAD 400+ (done)

Reruns:
AD 280 yrs (2.91%) --> SASU 240 yrs (12.67%) --> pSASU 60 yrs (2.51%)
AD 280 yrs (2.91%) --> pAD 580 yrs (5.22%)

**Comment by slevis-lmwg** [comment]
@wwieder @olyson 
The simulations have started.
Let me know if I misunderstood anything about the setup based on the details that I posted above.

**Comment by olyson** [comment]
Maybe it would be good to follow the comparison done by Cuijuan in her paper.  For the default CLM spinup (AD/pAD) she did 200 years of AD followed by at least 400 years of pAD.  For matrixcn, she did 200 years of AD mode, then 160 years of SASU, then 40 years of pAD.  In the end, she ended up with 3000 years of pAD in the standard spinup case to meet our equilibrium criteria and so demonstrated the speed of matrixcn.  She then compared the steady-state total ecosystem carbon and total soil carbon.  However, she did this on the sparse grid (400 grid cells).  And also something similar for a Brazil site.  So much faster than full global.  But maybe we can do this pretty fast at f45?  Also, both of the initial AD simulations were cold starts.

**Comment by slevis-lmwg** [comment]
Thanks, Keith. For starters then, I will stop the SASU case and start it up when AD generates a finidat at 200 yrs.

**Comment by olyson** [comment]
That sounds reasonable.  Is the AD case a cold start?

**Comment by slevis-lmwg** [comment]
Yes.

**Comment by slevis-lmwg** [comment]
@wwieder the simulations are done, so feel free to run your script(s) on the output.

**Comment by wwieder** [comment]
just to clarify, I should be comparing 

/glade/u/home/slevis/cases_LMWG_dev/ctsm51d159_f45_GSWP3_bgccrop_1850pAD

vs. 

/glade/derecho/scratch/slevis/archive/ctsm51d159_f45_GSWP3_bgccrop_1850pSASU

**Comment by slevis-lmwg** [comment]
Correct.

**Comment by olyson** [comment]
I've updated the description above to reference the new simulations where initial soil temperature is changed to 272K.  I think we'll also have to rerun the SASU/pSASU simulations since the SASU was initialized from the end of the AD?

**Comment by wwieder** [comment]
I guess that would be a cleaner comparison, although it seems like SASU isn't as strongly influenced by the initial pool sizes (unlike AD).  If it's not hard to do, maybe this makes sense.

Thanks Keith

**Comment by olyson** [comment]
@wwieder , @slevis-lmwg , the reruns were close to equilibrium before Derecho went down, so you could compare these two simulations:

/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850pSASU/lnd/hist
/glade/derecho/scratch/oleson/archive/ctsm51d159_f45_GSWP3_bgccrop_tsoiini_1850pAD/lnd/hist

**Comment by slevis-lmwg** [comment]
We have a cbalance error in the hist simulation:
The simulation started in 1850 (datm using 1901-1920) and crashed 80 timesteps (or so?) into 1901. I restarted from 1900-01-01 (most recent restart file) and got the same result b4b. I started hybrid from 1900-01-01 (same restart file) changing datm to use 1901-2014 and got the error but not b4b, presumably because datm was in 2014.

The error (startup and b4b restart):
```
dec0359.hsn.de.hpc.ucar.edu 259:  column cbalance error    =   3.217936017520587E-005          34
dec0359.hsn.de.hpc.ucar.edu 259:  is fates column?         =  F
dec0359.hsn.de.hpc.ucar.edu 259:  Latdeg,Londeg=  -36.9473684210527        145.000000000000
dec0359.hsn.de.hpc.ucar.edu 259:  begcb                    =    6751.39552603758
dec0359.hsn.de.hpc.ucar.edu 259:  endcb                    =    6751.37391112644
dec0359.hsn.de.hpc.ucar.edu 259:  delta store              =  -2.161491113565717E-002
dec0359.hsn.de.hpc.ucar.edu 259:  --- Inputs ---
dec0359.hsn.de.hpc.ucar.edu 259:  gpp                      =   0.000000000000000E+000
dec0359.hsn.de.hpc.ucar.edu 259:  --- Outputs ---
dec0359.hsn.de.hpc.ucar.edu 259:  er                       =   2.158273177092730E-002
dec0359.hsn.de.hpc.ucar.edu 259:  col_fire_closs           =   0.000000000000000E+000
dec0359.hsn.de.hpc.ucar.edu 259:  col_hrv_xsmrpool_to_atm  =   0.000000000000000E+000
dec0359.hsn.de.hpc.ucar.edu 259:  col_xsmrpool_to_atm      =   4.636403487949891E-012
dec0359.hsn.de.hpc.ucar.edu 259:  wood_harvestc            =   0.000000000000000E+000
dec0359.hsn.de.hpc.ucar.edu 259:  crop_harvestc_to_cropprodc =   0.000000000000000E+000
dec0359.hsn.de.hpc.ucar.edu 259:  -1*som_c_leached         =   8.174576120237008E-014
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: local  column   index = 34
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: global column   index = 46273
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: global landunit index = 4985
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: global gridcell index = 1668
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: gridcell longitude    =  145.0000000
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: gridcell latitude     =  -36.9473684
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: column   type         = 220
dec0359.hsn.de.hpc.ucar.edu 259: iam = 131: landunit type         = 2
dec0359.hsn.de.hpc.ucar.edu 259:  ENDRUN:
dec0359.hsn.de.hpc.ucar.edu 259:  ERROR: ERROR in CNBalanceCheckMod.F90 at line 384
```

I will start over with matrixcn turned off to confirm that it doesn't trigger the same error. If so, I will complete the run that way, to generate the 2000 finidat file that I need. Then we can also discuss whether to debug.
