### ISSUE TITLE
Coupled simulation with deadveg branch (f2000.ne30_t232.BGC_CROP.deadveg)

### ISSUE THREAD

**Issue by olyson** [NCAR/LMWG_dev#53]
**Description:**
Coupled simulation with the deadveg branch.
This is the coupled version of ctsm51_ctsm51d166deadveg_1deg_CRUJRA_FLDS_ABsnoCDE_blk_A5BCD_1850 (Issue #52 )

Purpose is again to see if increased vegetation at high northern latitudes can lower albedo in spring/early summer and cause earlier melt-out of the snowpack, and warm up the simulation at these latitudes.
___
**Case directory:**
Locally:
/glade/work/oleson/cesm2_3_alpha16g_deadveg/cime/scripts/f2000.ne30_t232.BGC_CROP.deadveg

___
**Sandbox:**
Locally:
/glade/work/oleson/cesm2_3_alpha16g_deadveg.
This is the cesm2_3_alpha16g tag with clm externals updated to the deadveg branch (https://github.com/olyson/ctsm/tree/deadveg).

 ___
**user_nl_ changes:**
user_nl_clm:

```
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
use_init_interp = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
finidat = '/glade/derecho/scratch/oleson/archive/ctsm51_ctsm51d166deadveg_1deg_CRUJRA_FLDS_ABsnoCDE_blk_A5BCD_1850pAD/rest/0601-01-01-00000/ctsm51_ctsm51d166deadveg_1deg_CRUJRA_FLDS_ABsnoCDE_blk_A5BCD_1850pAD.clm2.r.0601-01-01-00000.nc'
reseed_dead_plants = .true.

```

user_nl_cam:
```
fincl2 = 'TREFHT'
nhtfrq = 0,-24
mfilt  = 1,1
```
 ___
**SourceMods:**
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
src.clm/TemperatureType.F90: Set initial tsoisno for soil to 272K and for urban road to 274K

___
**Diagnostics:**

https://webext.cgd.ucar.edu/F2000climo/f2000.ne30_t232.BGC_CROP.deadveg/lnd/f2000.ne30_t232.BGC_CROP.deadveg_77_96-f2000.ne30_t232.BGC_CROP_77_96/setsIndex.html
___
**Output:**
/glade/scratch/oleson/archive/f2000.ne30_t232.BGC_CROP.deadveg
___
**Contacts:**
@olyson  
___
**Extra details:**

CLM Initial Conditions:
Currently setup using the end of the 1850pAD version of this configuration.  Could also wait for the historical using this configuration and using an initial file from that circa-year 2000.  But either way we'd be transitioning from CRUJRA to coupled model forcing, so I'm inclined not to wait for the historical.  Opinions, @slevis-lmwg , @wwieder ?

96 years completed.

**Comment by slevis-lmwg** [comment]
I say go for it. Could always run again with different finidat when it's available.

**Comment by olyson** [comment]
Complete through 96 years.  Diagnostics compared to the control https://github.com/NCAR/LMWG_dev/issues/14 in progress.
