### ISSUE TITLE
First iteration CTSM5.3 versus CTSM5.2 (issp245clm5[2, 3]bgccrop_f09)

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#59]
**Description:**
@slevis-lmwg submitted these simulations for @lawrencepj1.
The 5.3 case checks that the model works with the new data.
The 5.2 case is the control simulation for when Keith Oleson runs the diag. package on the two cases.
We did not perform a new spin-up for these runs.

Additional info in issue https://github.com/ESCOMP/CTSM/issues/2452

___
**Case directory:**
/glade/u/home/slevis/cases_ctsm5.2/issp245clm52bgccrop_f09
/glade/u/home/slevis/cases_ctsm5.3/issp245clm53bgccrop_f09
___
**Sandbox:**
/glade/work/slevis/git/mksurfdata_toolchain
git branch: new_rawpftlai
git describe: ctsm5.2.001-2-g24e9e191f
 ___
**user_nl_ changes:**
The 5.3 case has the following additions:
```
20,21d19
< fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/single_attempts/ssp/surfdata_0.9x1.25_SSP2-4.5_1850_78pfts_c240429.nc'
< flanduse_timeseries = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/single_attempts/ssp/landuse.timeseries_0.9x1.25_SSP2-4.5_1850-2100_78pfts_c240429.nc'
```
___
**SourceMods:**
NONE
___
**Diagnostics:**
ILAMB Diagnostics: https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/_build_newscore_regions/
Standard diagnostics: https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/setsIndex.html
___
**Output:**
/glade/derecho/scratch/slevis/issp245clm52bgccrop_f09/run
/glade/derecho/scratch/slevis/issp245clm53bgccrop_f09/run
I copied to
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_ctsm5.2/issp245clm52bgccrop_f09
/glade/campaign/cgd/tss/people/slevis/i_cases/cases_ctsm5.3/issp245clm53bgccrop_f09
___
**Contacts:**
@slevis-lmwg 
@lawrencepj1
___
**Extra details:**
For the 5.3 case (and similarly for the 5.2) `diff env_run.xml env_run.xml_1850-1919` returns
```diff
147c147
<     <entry id="RUN_TYPE" value="hybrid">
---
>     <entry id="RUN_TYPE" value="startup">
203c203
<     <entry id="RUN_REFDIR" value="/glade/derecho/scratch/slevis/archive/issp245clm53bgccrop_f09/rest/1920-01-01-00000">
---
>     <entry id="RUN_REFDIR" value="ccsm4_init">
209c209
<     <entry id="RUN_REFCASE" value="issp245clm53bgccrop_f09">
---
>     <entry id="RUN_REFCASE" value="case.std">
215c215
<     <entry id="RUN_REFDATE" value="1920-01-01">
---
>     <entry id="RUN_REFDATE" value="0001-01-01">
227c227
<     <entry id="GET_REFCASE" value="TRUE">
---
>     <entry id="GET_REFCASE" value="FALSE">
235c235
<     <entry id="RUN_STARTDATE" value="1920-01-01">
---
>     <entry id="RUN_STARTDATE" value="1850-01-01">
331c331
<     <entry id="CONTINUE_RUN" value="FALSE">
---
>     <entry id="CONTINUE_RUN" value="TRUE">
1108c1108
<     <entry id="DATM_YR_END" value="2014">
---
>     <entry id="DATM_YR_END" value="1920">
```

**Comment by olyson** [comment]
It's a sad commentary on the state of the land diagnostics package when ILAMB beats it in real-time.  ILAMB results are here:

https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/_build_newscore_regions/

Standard diagnostics are pending.

The global net ecosystem carbon balance trajectory doesn't look great in either of these simulations.  
The last deadveg historical we did was under CRUJRA forcing and didn't look great either but at least the land was a source at the end of the historical:

https://webext.cgd.ucar.edu/I20TR/ctsm51_ctsm51d166deadveg_1deg_CRUJRA_FLDS_ABsnoCDE_blk_A5BCD_hist/lnd/_build_newscore_regions_CLM50CTSM51DeadVegBGC/

**Comment by slevis-lmwg** [comment]
Thank you, @olyson 
@lawrencepj1 let us know what you think of the results when they are ready.

**Comment by lawrencepj1** [comment]
Thanks Sam @slevis-lmwg and Keith @olyson 

Great that you could perform both the CTSM5.3 and CTSM5.2 model runs and associated diagnostics. The ILAMB results only appear to have significant changes in Biomass, Net Ecosystem Carbon Balance, and the LAI/precipitation relationship. I agree with Keith that the large source in carbon from both runs over the historical period is concerning. From the other plots it looks like there are some small differences from the new datasets but they are small compared to other changes from older versions of the model. This is really apparent when looking at the CLM5, CTSM5.1 and Dead Veg results. 

The overall impact of the new Land Use data will be easier to determine once we have the Land Diagnostics posted but overall I think this change is an overall improvement of the historical transient terrestrial carbon cycle. From the work we are doing with the CCIS Ensemble with CESM2.1.5 we turned off shifting cultivation as it resulted in too high a historical transient CO2 growth rate in the emissions driven runs. I think that shifting cultivation is on now by default. Something to think about for the project and future simulations.

Thanks again
Peter

**Comment by olyson** [comment]
Standard diagnostics are here:

https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/setsIndex.html

**Comment by olyson** [comment]
I'm now confused as to the purpose of these simulations.  They use the ISSP245Clm50BgcCrop compset but are run for years 1850-2015 and they use GSWP3V1 forcing for those years.  But the streams settings in these historical runs are set for a future scenario and as such the simulations are not really historical simulations and it's not really appropriate to run these through ILAMB, right?

&ndepdyn_nml
 model_year_align_ndep = 2015
 ndep_taxmode = 'cycle'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/ndepdata/fndep_clm_f09_g17.CMIP6-SSP2-4.5-WACCM_1849-2101_monthly_c191007.nc'
 stream_meshfile_ndep = '/glade/campaign/cesm/cesmdata/inputdata/share/meshes/fv0.9x1.25_141008_polemod_ESMFmesh.nc'
 stream_year_first_ndep = 2015
 stream_year_last_ndep = 2101
/

&popd_streams
 model_year_align_popdens = 2015
 popdensmapalgo = 'bilinear'
 stream_fldfilename_popdens = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/firedata/clmforc.Li_2018_SSP2_CMIP6_hdm_0.5x0.5_AVHRR_simyr1850-2100_c181205.nc'
 stream_meshfile_popdens = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/firedata/clmforc.Li_2017_HYDEv3.2_CMIP6_hdm_0.5x0_ESMFmesh_cdf5_100621.nc'
 stream_year_first_popdens = 2015
 stream_year_last_popdens = 2100
/
&urbantv_streams
 model_year_align_urbantv = 2015
 stream_fldfilename_urbantv = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc'
 stream_meshfile_urbantv = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1_ESMFmesh_cdf5_100621.nc'
 stream_year_first_urbantv = 2015
 stream_year_last_urbantv = 2106
 urbantvmapalgo = 'nn'
/

etc.

**Comment by slevis-lmwg** [comment]
@olyson 
I started the 5.3 case to confirm that @lawrencepj1's new pft data didn't cause the model to crash. I used the ISSP245Clm50BgcCrop compset in case we wanted to run beyond 2015. I totally missed the fact that the streams settings were for the SSP period.

Originally Peter was going to follow up with his own simulations for further testing, but we decided instead to finish my test run and to compare it to an identical 5.2 case.

Since this is the evaluation phase, I will let Peter weigh in with his assessment and what may need to be done next.

**Comment by wwieder** [comment]
Peter, there seem to be small regional and seasonal differences [LAI](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set2/set2_MAM_TLAI.gif) and [GPP](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set2/set2_JJA_GPP.gif), which I'm assuming reflect changes in the PFT distributions in regions like China and southern Africa.

I'm confused by the ILAMB results, but maybe it doesn't matter given complications of configuration of datm streams?  Other historical runs with [modern code bases show a turn around in NBP](https://webext.cgd.ucar.edu/I1850/ctsm51_ctsm51d166deadveg_1deg_CRUJRA1940-1949_FLDS_ABsnoCDE_blk_A5BCD_hist/lnd/_build_newscore_regions_DeadVegBGC_1940-1949_1901-1920/EcosystemandCarbonCycle/GlobalNetEcosystemCarbonBalance/GCP/GCP.html) related to CO2 fertilization.

**Comment by wwieder** [comment]
[Total Veg C differences are non-zero](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set2/set2_ANN_TOTVEGC.gif) and maybe hard to assess without a spinup, but do these patterns seem reason able given chagnes to PFT distributions, Peter?

**Comment by lawrencepj1** [comment]
Thanks everyone @wwieder @olyson @slevis-lmwg 

The major changes between the CTSM52 and CTSM53 simulations are the use of climate surfaces in generating the potential vegetation and an update on the CFT composition. Independent of the configuration of the streams files these two simulations demonstrate that the impact is relative small. All of the global and regional plots for moisture energy and carbon fluxes and pools are almost identical.

The biggest changes are:

The surface datasets have slightly higher early 1850 - 1950 land use change flux and slightly lower 1980 land use change flux. 
See [here](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set1/set1_DWT_CONV_CFLUX.gif) 

The wood harvest is slightly lower across the time period.
See [here](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set1/set1_WOOD_HARVESTC.gif)

The combination of the two account for the difference in Total Ecosystem Carbon [here](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set1/set1_TOTECOSYSC.gif)

Which is essentially all in Total Vegetation Carbon [here](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/issp245clm53bgccrop_f09_1996_2015-issp245clm52bgccrop_f09_1996_2015/set1/set1_TOTVEGC.gif)

Sam and Keith, my apologies for not doing these simulations as I was hoping they would be relatively simple and would not be a big distraction to your already over subscribed time. 

Will, yes the differences are small and inline with what I was anticipating for the surface dataset changes. I am still concerned that the Shifting Cultivation is a major cause for the lack of carbon uptake across the historical period. This is why we turned it off for the CLM5 CCIS Ensemble simulations.

Thanks everyone
Peter

**Comment by wwieder** [comment]
hmmm, your last comment is an interesting one, @lawrencepj1.  My initial thought is that we'd need higher productivity to overcome the effects of shifting cultivation and maintain our land C sink.  This would be consistent with work Heather Graven presented at the LMWG meeting in February. It also seem like something we should be able to calibrate in the PPE?  maybe before we default to turning off shifting cultivation, it's worth a discussion with the larger CLM team?

More immediately, are there additional analyses or simulations we need to consider before accepting changes and making a 5.3 tag?

**Comment by olyson** [comment]
How is shifting cultivation turned on/off?

**Comment by slevis-lmwg** [comment]
I think with do_grossunrep

**Comment by olyson** [comment]
That's what I had thought as well.  do_grossunrep is already .false. in both of these simulations.

**Comment by lawrencepj1** [comment]
Thanks @olyson and @slevis-lmwg 

Good to know. Then I guess all I can say is don't turn it on then. Good to have lots of working hypotheses.

Cheers
Peter

**Comment by wwieder** [comment]
@lawrencepj1 are additional analyses needed or are you comfortable moving forward with the pr for 5.3 datasets?

**Comment by lawrencepj1** [comment]
@wwieder @slevis-lmwg @olyson 

Thanks for all your work in getting the data into the CTSM5.2 format, running simulations and performing diagnostics. From the analysis there are no major differences in the simulations with the CTSM5.2 and CTSM5.3 PFT and CFT datasets for most fields at global levels. The new datasets do result in improvements for both the spatial generation of potential vegetation and in the crop distributions and breakdown compared to the UNFAO and EarthSTAT data. Additionally the new datasets are beneficial to the historical carbon cycle trajectory reducing the differences with the [Global Carbon Project](https://webext.cgd.ucar.edu/I20TR/issp245clm53bgccrop_f09/lnd/_build_newscore_regions/EcosystemandCarbonCycle/GlobalNetEcosystemCarbonBalance/GCP/GCP.html)

So yes, confirming that I am comfortable in including the new data in the PR for the 5.3 datasets.

Thanks again
Peter
