### ISSUE TITLE
CESM3-SP test (b.e23_alpha16b BLT1850 ne30_t232 034SP)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#6]
**Description:**
Same as b.e23_alpha16b.BLT1850.ne30_t232.034 (cloned) but with CLM satellite phenology (SP) instead of BGC.
Purpose is to see if increased vegetation at high northern latitudes can lower albedo in spring/early summer and cause earlier melt-out of the snowpack, and warm up the simulation at these latitudes.
___
**Case directory:**
Locally:
/glade/work/oleson/cesm2_3_alpha16b_runs/b.e23_alpha16b.BLT1850.ne30_t232.034SP
___
**Sandbox:**
Locally:
/glade/work/hannay/cesm_tags/cesm2_3_alpha16b
 ___
**user_nl_ changes:**
use_init_interp = .true.
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
finidat='/glade/p/cgd/tss/people/oleson/CLM5_restarts/ctsm51_cesm23a14a_ne30pg3ne30pg3mg17_CPLHIST_1850pAD.clm2.r.0561-01-01-00000.nc'
 ___
**SourceMods:**
src.clm/clm_varpar.F90: nlevurb=5 -> nlevurb=10
src.clm/surfrdMod.F90: Remove read of PFTDATA_MASK
___
**Diagnostics:**
Diags (if available)

[Here](https://webext.cgd.ucar.edu/BLT1850/b.e23_alpha16b.BLT1850.ne30_t232.034SP/lnd/b.e23_alpha16b.BLT1850.ne30_t232.034SP.5_6-b.e23_alpha16b.BLT1850.ne30_t232.034.5_6/setsIndex.html)
___
**Output:**
Output:
/glade/campaign/cgd/tss/common/Coupled_Simulations/CTSM52_DEV/b.e23_alpha16b.BLT1850.ne30_t232.034SP
___
**Contacts:**
@olyson
___
**Extra details:**
See discussion in https://github.com/NCAR/LMWG_dev/discussions/3
Complete

**Comment by slevis-lmwg** [comment]
@olyson @adamrher 
This case includes some src.cam mods. Initially I included them in my F-case #13 and failed due to a history var not appearing in the master list. I have decided to omit these mods altogether in #13, unless you recommend otherwise.

**Comment by adamrher** [comment]
Hi @slevis-lmwg the SourceMods in https://github.com/NCAR/amwg_dev/issues/361 should be included. They provide Ri based diffusion above here clubb is active. I don't expect this to have a first order impact of the radiative balance. 

Looks liken you're basing these runs on coupled baseline 34, which is fine, but note 34 is a bit colder than our more recent runs (38-44). Moving targets are always a challenge ...
