### ISSUE TITLE
1850 + hist with ctsm5.3 fsurdat, excess ice ON, A/C ON (ctsm52018_f09_xsiceON_acON_[AD, SASU, pSASU, hist])

### ISSUE THREAD

**Issue by slevis-lmwg** [NCAR/LMWG_dev#62]
**Description:**
Year-1850 spin-up with ctsm5.2.018 but with excess ice ON, A/C ON, and ctsm53 fsurdat file. DATM input from TRENDY as in #60 and #61.

- 1850 AD DONE (startup)
- 1850 SASU DONE (hybrid) --> HAD TO RESOLVE MISSING excess_ice_streams STUFF + INCLUDE `nnegcrit = -7.d0`
- 1850 pSASU DONE (hybrid)
- 1850-2023 hist (hybrid)
___
**Case directory:**
Locally:
~slevis/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_AD
~slevis/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_SASU
~slevis/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_pSASU
~slevis/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_hist
___
**Sandbox:**
Locally:
/glade/work/slevis/git/LMWG_dev8
git branch returns ctsm5.2.018
git describe returns ctsm5.2.018
 ___
**user_nl_ changes:**
AD
```
urban_explicit_ac = .true.
use_excess_ice = .true.

fsurdat='/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_0.9x1.25_hist_1850_78pfts_c240807.nc'

! turn off shifting cultivation
do_grossunrep = .false.

! do this for spinup
reseed_dead_plants = .true.

! do this for isotopes
use_c13 = .true.
use_c14 = .true.
use_c13_timeseries = .true.
use_c14_bombspike = .true.
```
SASU also includes missing excess ice stream stuff and updated nnegcrit
```
stream_fldfilename_exice = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/exice_init_0.125x0.125_c20220516.nc'
stream_mapalgo_exice = 'bilinear'
stream_meshfile_exice = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/exice_init_0.125x0.125_ESMFmesh_cdf5_c20220802.nc'
use_excess_ice_streams = .true.

finidat = '/glade/derecho/scratch/slevis/archive/ctsm52018_f09_xsiceON_acON_AD/rest/0301-01-01-00000/ctsm52018_f09_xsiceON_acON_AD.clm2.r.0301-01-01-00000.nc'
nnegcrit = -7.d0
```
pSASU will include
```
finidat = '/glade/derecho/scratch/slevis/archive/ctsm52018_f09_xsiceON_acON_SASU/rest/0241-01-01-00000/ctsm52018_f09_xsiceON_acON_SASU.clm2.r.0241-01-01-00000.nc'
```
hist vs. pSASU
```
5c5,6
<  co2_type = 'diagnostic'
---
>  co2_ppmv = 284.7
>  co2_type = 'constant'
13c14
<  finidat = '/glade/derecho/scratch/slevis/archive/ctsm52018_f09_xsiceON_acON_pSASU/rest/0201-01-01-00000/ctsm52018_f09_xsiceON_acON_pSASU.clm2.r.0201-01-01-00000.nc'
---
>  finidat = '/glade/derecho/scratch/slevis/archive/ctsm52018_f09_xsiceON_acON_SASU/rest/0301-01-01-00000/ctsm52018_f09_xsiceON_acON_SASU.clm2.r.0301-01-01-00000.nc'
28c29
<  irrigate = .true.
---
>  irrigate = .false.
71d71
<  use_init_interp = .true.
86,87c86
<  model_year_align_ndep = 1850
<  ndep_taxmode = 'extend'
---
>  ndep_taxmode = 'cycle'
90c89
<  stream_fldfilename_ndep = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/ndepdata/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc'
---
>  stream_fldfilename_ndep = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/ndepdata/fndep_clm_WACCM6_CMIP6piControl001_y21-50avg_1850monthly_0.95x1.25_c180802.nc'
93c92
<  stream_year_last_ndep = 2015
---
>  stream_year_last_ndep = 1850
96d94
<  model_year_align_popdens = 1850
101c99
<  stream_year_last_popdens = 2016
---
>  stream_year_last_popdens = 1850
104d101
<  model_year_align_urbantv = 1850
108c105
<  stream_year_last_urbantv = 2106
---
>  stream_year_last_urbantv = 1850
168,173d164
<  do_harvest = .true.
<  do_transient_crops = .true.
<  do_transient_lakes = .true.
<  do_transient_pfts = .true.
<  do_transient_urban = .true.
<  flanduse_timeseries = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/landuse.timeseries_0.9x1.25_hist_1700-2023_78pfts_c240731.nc'
182d172
<  check_dynpft_consistency = .false.
185d174
<  init_interp_method = 'general'
331a321
>  reseed_dead_plants = .true.
355a346,349
>  stream_fldfilename_exice = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/exice_init_0.125x0.125_c20220516.nc'
>  stream_mapalgo_exice = 'bilinear'
>  stream_meshfile_exice = '/glade/campaign/cesm/cesmdata/inputdata/lnd/clm2/paramdata/exice_init_0.125x0.125_ESMFmesh_cdf5_c20220802.nc'
>  use_excess_ice_streams = .true.
```
The last few lines about excess_ice_streams are correct. Matvey explained to me that it doesn't hurt to include them, but they are required ONLY in the coldstart case.

user_nl_datm_streams same as in #60 and #61.
 ___
**SourceMods:**
NONE
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
Output (if still available):
/glade/scratch/$USER/archive/$CASE/
___
**Contacts:**
@slevis-lmwg 
___
**Extra details:**
```
./create_newcase --case ~/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_AD --compset I1850Clm60BgcCropCru --res f09_g17 --project P08010000 --user-mods-dirs /glade/work/afoster/TRENDY_2024/user_mods/ADspinup --run-unsupported
./create_clone --clone ~/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_AD/ --case ~/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_SASU
./create_clone --clone ~/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_SASU/ --case ~/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_pSASU
./create_newcase --case /glade/u/home/slevis/cases_LMWG_dev/ctsm52018_f09_xsiceON_acON_hist --compset IHistClm60BgcCrop --res f09_g17 --run-unsupported
```
Sequence of simulations:
1850AD 300 yrs --> 1850SASU 240 yrs --> 1850pSASU 240 yrs (At least 97% of the land surface is in TOTECOSYSC equilibrium. Eq. Yr. = 201)

**Comment by olyson** [comment]
I'm starting to look at this setup so that I can do a parallel Sturm perturbation spinup.
I see that there are user mods which include user_nl_cpl, which seems to specify orbital parameters for 1700 consistent with TRENDY, but this is an 1850 spinup.

**Comment by slevis-lmwg** [comment]
Thanks for catching that. I will correct.

**Comment by olyson** [comment]
Per this discussion here: https://github.com/NCAR/LMWG_dev/discussions/23, I was thinking we had decided to use CRUJRA FLDS, not CLM calculated FLDS.  Does that apply here?  It's looks like we are using CLM calculated FLDS here?

**Comment by slevis-lmwg** [comment]
> Per this discussion here: #23, I was thinking we had decided to use CRUJRA FLDS, not CLM calculated FLDS. Does that apply here? It's looks like we are using CLM calculated FLDS here?

That's an interesting point:
- I will let @wwieder make the call for this spin-up
- I'm including @adrifoster in the discussion since it pertains to the TRENDY simulations, as well

**Comment by wwieder** [comment]
I would assume we want to use CRU-JRA incoming shortwave for these new simulations.  From what I recall in the cases you reference above we don't see the declines in FLDS over the historical periods that were characteristic of older CRU-based products.  We also saw earlier snow melt when using the DATM provided FLDS (instead of the CLM calculated values).

Just to reiterate, for the excess ice ON and STURM-mods in #63 let's use CRU-JRA FLDS datm inputs.

**Comment by slevis-lmwg** [comment]
I have updated the user_nl_datm_streams appropriately.

**Comment by slevis-lmwg** [comment]
@olyson I will make some updates to #63 to match 62.

**Comment by adrifoster** [comment]
@olyson and @slevis-lmwg thanks for finding this and letting me know. I will resubmit my TRENDY runs... 😭
