### ISSUE TITLE
reduce nstem (enter the name of the run here)

### ISSUE THREAD

**Issue by wwieder** [NCAR/LMWG_dev#9]
**Description:**

Given the importance of reducing `nstem` in the coupled PPE and OAT simulations that's been discussed in #3, let's try reducing this for arctic shrubs and C3 grasses. 
___
**Case directory:**
Locally:
/glade/work/$USER/$TAG/cime/scripts/$CASE
___
**Sandbox:**
Locally:
 /glade/work/$USER/$TAG
 ___
**user_nl_ changes:**

 ___
**SourceMods:**

___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/I1850/$CASE/lnd/](https://webext.cgd.ucar.edu/I2000/$CASE/lnd/)
___
**Output:**
Output (if still available):
/glade/scratch/$USER/archive/$CASE/
___
**Contacts:**
@olyson
___
**Extra details:**

**Comment by wwieder** [comment]
@slevis-lmwg can you do these simulations (similar to others in the #3 discussion)?  There's still some uncertainty on how low to [reduce nstem in this thread](https://github.com/NCAR/LMWG_dev/discussions/3#discussioncomment-6991485).  I think it's -30%, but am unsure...

**Comment by slevis-lmwg** [comment]
From what Keith and I understood from the CLM meeting just now, I should not proceed with this case and can close the issue. We can reopen if we change our minds.

Keith and I discussed the coupled case that I should start next, and I will open an issue for it.
